

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>


<?php if ($this->isUserEnrolled()): ?>

	<?php $player = $this->getPlayer(); ?>

	<h4>Welcome <?php echo $player->getUsername() ?>!</h4>

	<br />
	<br />

	<p>Current Hearts: <b><?php echo $player->getPointsCurrent() ?></b></p>
	<p>Current Money: <b><?php echo $player->getMoneyCurrent() ?></b></p>


<?php else: ?>

	<p>You are not enrolled, enter a username to get started.</p>

	<br />

	<form action="<?php echo $this->getUrl('capitalism/index/enroll') ?>" method="post">
		<input type="text" name="new_username"/>
		<input type="submit" value="Start"/>
	</form>


<?php endif; ?>

